version: "3.1"

services:
  #This handles all of the http request to simple cert issues and both the SP and IdP can share the same ports.
  httpd-proxy:
    build: ./httpd-proxy/
    ports:
     - "8444:443"
    depends_on:
      - idp

  idp:
    build:
      context: ./idp/
      args:
        HOSTNAME_FOR_BROWSER: ${HOSTNAME_FOR_BROWSER:-idptestbed}
    command: []
    depends_on: 
      ldap:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose: 
     - "4443"
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer     

  ldap:
    build: ./ldap/

  mysql:
    image: mysql:5.7.42
    environment:
      #- MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=t
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01-shib.sql
    healthcheck:
      test: ["CMD-SHELL", "mysql shibboleth >/dev/null 2>&1 </dev/null"]
      start_period: 10s

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
